const Adj3 = [
  { verbo: "rude", respuesta: ["maleducado", "grosero", "tosco"] },
  { verbo: "sad", respuesta: ["triste", "lamentable", "penoso"] },
  { verbo: "safe", respuesta: ["seguro"] },
  { verbo: "salty", respuesta: ["salado"] },
  { verbo: "sane", respuesta: ["cuerdo", "sensato", "sano"] },
  { verbo: "scary", respuesta: ["espantoso", "asustadizo"] },
  { verbo: "shallow", respuesta: ["superficial"] },
  { verbo: "shiny", respuesta: ["brillante", "reluciente"] },
  { verbo: "short", respuesta: ["corto", "bajo", "chaparro"] },
  { verbo: "shy", respuesta: ["timido"] },
  { verbo: "silly", respuesta: ["tonto"] },
  { verbo: "simple", respuesta: ["simple", "sencillo", "facil"] },
  { verbo: "sincere", respuesta: ["sincero", "genuino"] },
  { verbo: "skinny", respuesta: ["flaco"] },
  { verbo: "sleepy", respuesta: ["adormilado", "soñoliento"] },
  { verbo: "slim", respuesta: ["delgado", "fino"] },
  { verbo: "slimy", respuesta: ["viscoso", "pegajoso", "empalagoso"] },
  { verbo: "slow", respuesta: ["lento"] },
  { verbo: "small", respuesta: ["pequeño"] },
  { verbo: "smart", respuesta: ["listo", "inteligente", "agudo"] },
  { verbo: "smelly", respuesta: ["apestoso"] },
  { verbo: "smooth", respuesta: ["liso", "suave", "llano", "fluido"] },
  { verbo: "soft", respuesta: ["blando", "suave"] },
  { verbo: "soon", respuesta: ["pronto"] },
  { verbo: "sorry", respuesta: ["lamentable"] },
  { verbo: "spicy", respuesta: ["picante", "especiado", "sazonado"] },
  { verbo: "stingly", respuesta: ["tacaño", "racano", "raquitico"] },
  { verbo: "strange", respuesta: ["raro", "extraño", "desconocido"] },
  { verbo: "strict", respuesta: ["estricto", "rigido"] },
  { verbo: "strong", respuesta: ["fuerte", "solido", "intenso", "marcado"] },
  { verbo: "sunny", respuesta: ["soleado", "radiante"] },
  { verbo: "sweaty", respuesta: ["sudoroso"] },
  { verbo: "sweet", respuesta: ["dulce"] },
  { verbo: "tall", respuesta: ["alto"] },
  { verbo: "tan", respuesta: ["bronceado", "moreno"] },
  { verbo: "tasty", respuesta: ["rico", "sabroso", "apetitoso"] },
  { verbo: "thin", respuesta: ["delgado", "fino"] },
  { verbo: "thirsty", respuesta: ["sediento"] },
  { verbo: "tiny", respuesta: ["diminuto", "minusculo"] },
  { verbo: "ugly", respuesta: ["feo"] },
  { verbo: "warm", respuesta: ["caliente", "templado", "calido"] },
  { verbo: "weak", respuesta: ["debil", "flojo"] },
  { verbo: "weird", respuesta: ["raro", "extraño"] },
  { verbo: "wet", respuesta: ["mojado", "humedo", "lluvioso"] },
  { verbo: "wide", respuesta: ["ancho", "amplio", "extenso"] },
  { verbo: "wild", respuesta: ["salvaje", "silvestre", "descontrolado"] },
  { verbo: "windy", respuesta: ["ventoso"] },
  { verbo: "wise", respuesta: ["sabio", "sensato", "prudente"] },
  { verbo: "worldly", respuesta: ["mundano", "terreno"] },
  { verbo: "young", respuesta: ["joven"] },
];

export default Adj3;
