const VerbosD = [
  { verbo: "readability", respuesta: ["legibilidad"] },
  { verbo: "lockdown", respuesta: ["confinamiento"] },
  { verbo: "destabilising", respuesta: ["desestabilizador"] },
  { verbo: "unlawfully", respuesta: ["ilegalmente"] },
  { verbo: "springboard", respuesta: ["trampolin"] },
  { verbo: "roadblock", respuesta: ["barricada"] },
  { verbo: "shipwrecked", respuesta: ["naufrago"] },
  { verbo: "enviromental", respuesta: ["ambiental"] },
  { verbo: "acknowledge", respuesta: ["reconocer"] },
  { verbo: "issuing", respuesta: ["emisor"] },
  { verbo: "dock", respuesta: ["muelle"] },
  { verbo: "lingering", respuesta: ["persistente"] },
  { verbo: "thrive", respuesta: ["prosperar"] },
  { verbo: "rife", respuesta: ["abundante"] },
  { verbo: "appliances", respuesta: ["electrodomesticos"] },
  { verbo: "ruling", respuesta: ["fallo"] },
  { verbo: "undermine", respuesta: ["socavar"] },
  { verbo: "western", respuesta: ["occidental"] },
  { verbo: "stints", respuesta: ["temporadas"] },
  { verbo: "abroad", respuesta: ["extranjero"] },
  { verbo: "drilling", respuesta: ["perforacion"] },
  { verbo: "overturning", respuesta: ["anular"] },
  { verbo: "drought", respuesta: ["sequia"] },
  { verbo: "shortages", respuesta: ["escazes"] },
  { verbo: "etched", respuesta: ["grabado"] },
  { verbo: "sweep", respuesta: ["barrer"] },
  { verbo: "seeks", respuesta: ["busca"] },
  { verbo: "leisurely", respuesta: ["tranquilo", "ralajado", "sin prisa"] },
  { verbo: "raving", respuesta: ["delirante"] },
  { verbo: "swamp", respuesta: ["pantano"] },
  { verbo: "plotting", respuesta: ["trazar", "tramar", "graficado"] },
  { verbo: "prosecute", respuesta: ["procesado"] },
  { verbo: "tauting", respuesta: ["burlandose", "burlar"] },
  { verbo: "rubbed", respuesta: ["frotado", "frotar"] },
  { verbo: "hang", respuesta: ["colgar"] },
];

export default VerbosD;
