

const Adj2 = [
                    {verbo: "good",respuesta: ["bueno"]},
                    {verbo: "grand",respuesta: ["grandioso","ambicioso"]},
                    {verbo: "greasy",respuesta: ["grasiento"]},
                    {verbo: "great",respuesta: ["grande","genial"]},
                    {verbo: "gross",respuesta: ["asqueroso","grosero"]},
                    {verbo: "guilty",respuesta: ["culpable"]},
                    {verbo: "hairy",respuesta: ["velludo","peludo"]},
                    {verbo: "happy",respuesta: ["feliz","contento","alegre"]},
                    {verbo: "hard",respuesta: ["duro","dificil"]},
                    {verbo: "healthy",respuesta: ["sano","saludable"]},
                    {verbo: "heavy",respuesta: ["pesado","grueso","fuerte","duro"]},
                    {verbo: "high",respuesta: ["alto","elevando","agudo"]},
                    {verbo: "hot",respuesta: ["caliente","picante","caluroso"]},
                    {verbo: "hungry",respuesta: ["hambriento"]},
                    {verbo: "icy",respuesta: ["helado","frio"]},
                    {verbo: "itchy",respuesta: ["picante"]},
                    {verbo: "kind",respuesta: ["amable","bueno","bondadoso"]},
                    {verbo: "large",respuesta: ["grande"]},
                    {verbo: "lazy",respuesta: ["perezoso"]},
                    {verbo: "light",respuesta: ["ligero","claro","liviano"]},
                    {verbo: "little",respuesta: ["pequeño","poco"]},
                    {verbo: "lonely",respuesta: ["solitario"]},
                    {verbo: "long",respuesta: ["largo"]},
                    {verbo: "lovely",respuesta: ["precioso","bello","lindo"]},
                    {verbo: "low",respuesta: ["bajo"]},
                    {verbo: "mad",respuesta: ["enfadado","enojado","loco"]},
                    {verbo: "mean",respuesta: ["malo","mezquino","tacaño"]},
                    {verbo: "messy",respuesta: ["sucio","desordenado","desastroso"]},
                    {verbo: "nasty",respuesta: ["desagradable"]},
                    {verbo: "naughty",respuesta: ["malo","travieso","picaro"]},
                    {verbo: "near",respuesta: ["cercano","proximo"]},
                    {verbo: "neat",respuesta: ["ordenado","aseado","pulcro"]},
                    {verbo: "needy",respuesta: ["necesario"]},
                    {verbo: "new",respuesta: ["nuevo","fresco","reciente","moderno"]},
                    {verbo: "nice",respuesta: ["simpatico","agradable","bueno"]},
                    {verbo: "noisy",respuesta: ["ruidoso","clamoroso"]},
                    {verbo: "old",respuesta: ["viejo","antiguo","anciano"]},
                    {verbo: "plain",respuesta: ["claro","sencillo"]},
                    {verbo: "polite",respuesta: ["educado","cortes"]},
                    {verbo: "poor",respuesta: ["pobre"]},
                    {verbo: "pretty",respuesta: ["bonito","lindo","hermoso"]},
                    {verbo: "proud",respuesta: ["orgulloso","soberbio","digno"]},
                    {verbo: "pure",respuesta: ["puro"]},
                    {verbo: "quick",respuesta: ["rapido"]},
                    {verbo: "quiet",respuesta: ["tranquilo","silencioso"]},
                    {verbo: "rare",respuesta: ["raro"]},
                    {verbo: "rich",respuesta: ["rico","abundante"]},
                    {verbo: "risky",respuesta: ["arriesgado","peligroso"]},
                    {verbo: "roomy",respuesta: ["espacioso"]},
                    {verbo: "rough",respuesta: ["aspero","tosco","bruto","ronco"]},
                    
    
]

export default Adj2;