const Adj1 = [
                    {verbo: "angry",respuesta: ["enfadado","enojado"]},
                    {verbo: "bad",respuesta: ["malo"]},
                    {verbo: "big",respuesta: ["grande"]},
                    {verbo: "bitter",respuesta: ["amargo"]},
                    {verbo: "black",respuesta: ["negro"]},
                    {verbo: "bossy",respuesta: ["mandon"]},
                    {verbo: "brave",respuesta: ["valiente"]},
                    {verbo: "brief",respuesta: ["breve"]},
                    {verbo: "bright",respuesta: ["brillante","luminoso"]},
                    {verbo: "broad",respuesta: ["ancho","amplio"]},
                    {verbo: "busy",respuesta: ["ocupado","ajetreado"]},
                    {verbo: "calm",respuesta: ["tranquilo"]},
                    {verbo: "cheap",respuesta: ["barato","economico"]},
                    {verbo: "clean",respuesta: ["limpio","sano"]},
                    {verbo: "clear",respuesta: ["claro","despejado"]},
                    {verbo: "clever",respuesta: ["listo","ingenioso"]},
                    {verbo: "close",respuesta: ["cerca"]},
                    {verbo: "cloudy",respuesta: ["nublado"]},
                    {verbo: "clumsy",respuesta: ["torpe"]},
                    {verbo: "cold",respuesta: ["frio"]},
                    {verbo: "cool",respuesta: ["fresco"]},
                    {verbo: "crazy",respuesta: ["loco"]},
                    {verbo: "creepy",respuesta: ["espeluznante","repugnante"]},
                    {verbo: "crispy",respuesta: ["crujiente"]},
                    {verbo: "cruel",respuesta: ["cruel"]},
                    {verbo: "crunchy",respuesta: ["crujiente"]},
                    {verbo: "curvy",respuesta: ["curvo"]},
                    {verbo: "dark",respuesta: ["oscuro","moreno"]},
                    {verbo: "deadly",respuesta: ["mortal","mortifero"]},
                    {verbo: "deep",respuesta: ["profundo"]},
                    {verbo: "dense",respuesta: ["denso"]},
                    {verbo: "dirty",respuesta: ["sucio"]},
                    {verbo: "dry",respuesta: ["seco"]},
                    {verbo: "dull",respuesta: ["aburrido","sonso","apagado"]},
                    {verbo: "dumb",respuesta: ["tonto"]},
                    {verbo: "early",respuesta: ["temprano"]},
                    {verbo: "easy",respuesta: ["facil"]},
                    {verbo: "faint",respuesta: ["leve","tenue","palido","ligero"]},
                    {verbo: "fancy",respuesta: ["lujoso"]},
                    {verbo: "far",respuesta: ["lejos","distante"]},
                    {verbo: "fast",respuesta: ["rapido"]},
                    {verbo: "fat",respuesta: ["gordo"]},
                    {verbo: "few",respuesta: ["pocos"]},
                    {verbo: "firm",respuesta: ["firme","estricto"]},
                    {verbo: "fit",respuesta: ["apto","en forma"]},
                    {verbo: "fresh",respuesta: ["fresco","nuevo","original"]},
                    {verbo: "friendly",respuesta: ["agradable","amable","amistoso"]},
                    {verbo: "full",respuesta: ["lleno","completo"]},
                    {verbo: "funny",respuesta: ["gracioso","curioso","raro"]},
                    {verbo: "gloomy",respuesta: ["pesimista","abatido","decaido"]},
                ]


export default Adj1;