const Preps = [
                        {verbo: "after",respuesta: ["despues de"]},
                        {verbo: "around",respuesta: ["alrededor de"]},
                        {verbo: "at",respuesta: ["en"]},
                        {verbo: "before",respuesta: ["antes"]},
                        {verbo: "between",respuesta: ["entre"]},
                        {verbo: "by",respuesta: ["por"]},
                        {verbo: "during",respuesta: ["durante"]},
                        {verbo: "from",respuesta: ["de","desde"]},
                        {verbo: "on",respuesta: ["en"]},
                        {verbo: "since",respuesta: ["desde"]},
                        {verbo: "to",respuesta: ["a"]},
                        {verbo: "until",respuesta: ["hasta"]},
                        {verbo: "above",respuesta: ["encima"]},
                        {verbo: "against",respuesta: ["contra"]},
                        {verbo: "at",respuesta: ["en"]},
                        {verbo: "below",respuesta: ["debajo de"]},
                        {verbo: "beneath",respuesta: ["bajo"]},
                        {verbo: "beside",respuesta: ["al lado de"]},
                        {verbo: "in",respuesta: ["en"]},
                        {verbo: "next to",respuesta: ["proximo a"]},
                        {verbo: "on",respuesta: ["en"]},
                        {verbo: "under",respuesta: ["debajo"]},
                        {verbo: "across",respuesta: ["a traves de"]},
                        {verbo: "into",respuesta: ["en"]},
                        {verbo: "onto",respuesta: ["en","sobre"]},
                        {verbo: "over",respuesta: ["encima"]},
                        {verbo: "through",respuesta: ["a traves de"]},
    
]

export default Preps;