const VerbosE = [{verbo: "dog",respuesta: ["perro"]},
                {verbo: "cat",respuesta: ["gato"]},
                {verbo: "mouse",respuesta: ["raton"]},
                {verbo: "pig",respuesta: ["cerdo","chancho"]},
                {verbo: "lion",respuesta: ["leon"]},
                {verbo: "horse",respuesta: ["caballo"]},
                {verbo: "monkey",respuesta: ["mono"]},
                {verbo: "bear",respuesta: ["oso"]},
                {verbo: "snake",respuesta: ["serpiente"]},
                {verbo: "turtle",respuesta: ["tortuga"]},
                {verbo: "giraffe",respuesta: ["jirafa"]},
                {verbo: "elephant",respuesta: ["elefante"]},
                {verbo: "duck",respuesta: ["pato"]},
                {verbo: "bird",respuesta: ["pajaro"]},
                {verbo: "cow",respuesta: ["vaca"]},
                {verbo: "red",respuesta: ["rojo"]},
                {verbo: "blue",respuesta: ["azul"]},
                {verbo: "yellow",respuesta: ["amarillo"]},
                {verbo: "green",respuesta: ["verde"]},
                {verbo: "pink",respuesta: ["rosa"]},
                {verbo: "orange",respuesta: ["naranja"]},
                {verbo: "purple",respuesta: ["morado","purpura"]},
                {verbo: "violet",respuesta: ["violeta"]},
                {verbo: "brown",respuesta: ["marron"]},
                {verbo: "gray",respuesta: ["gris"]},
                {verbo: "black",respuesta: ["negro"]},
                {verbo: "white",respuesta: ["blanco"]},
                {verbo: "car",respuesta: ["auto"]},
                {verbo: "bike",respuesta: ["bicicleta"]},
                {verbo: "door",respuesta: ["puerta"]},
                {verbo: "window",respuesta: ["ventana"]},
                {verbo: "chair",respuesta: ["silla"]},
                {verbo: "book",respuesta: ["libro"]},
                {verbo: "mirror",respuesta: ["espejo"]},
                {verbo: "closet",respuesta: ["armario","ropero"]},
                {verbo: "bathroom",respuesta: ["baño"]},
                {verbo: "bedroom",respuesta: ["dormitorio"]},
                {verbo: "kitchen",respuesta: ["cocina"]},
                {verbo: "garden",respuesta: ["jardin"]},
                {verbo: "screen",respuesta: ["pantalla"]},
                {verbo: "keyboard",respuesta: ["teclado"]},
                {verbo: "left",respuesta: ["izquierda"]},
                {verbo: "rigth",respuesta: ["derecha"]},
                {verbo: "up",respuesta: ["arriba"]},
                {verbo: "down",respuesta: ["abajo"]},
                {verbo: "water",respuesta: ["agua"]},
                {verbo: "fire",respuesta: ["fuego"]},
                {verbo: "air",respuesta: ["aire"]},
                {verbo: "earth",respuesta: ["tierra"]},
                {verbo: "programmer",respuesta: ["programador"]},
                
]

export default VerbosE;

