let VerbosE = [{verbo: "dog",respuesta: "perro"},
                {verbo: "cat",respuesta: "gato"},
                {verbo: "mouse",respuesta: "raton"},
                {verbo: "pig",respuesta: "cerdo"},
                {verbo: "lion",respuesta: "leon"},
                {verbo: "horse",respuesta: "caballo"},
                {verbo: "monkey",respuesta: "mono"},
                {verbo: "bear",respuesta: "oso"},
                {verbo: "snake",respuesta: "serpiente"},
                {verbo: "turtle",respuesta: "tortuga"},
                {verbo: "giraffe",respuesta: "jirafa"},
                {verbo: "elephant",respuesta: "elefante"},
                {verbo: "duck",respuesta: "pato"},
                {verbo: "bird",respuesta: "pajaro"},
                {verbo: "cow",respuesta: "vaca"},
                {verbo: "hello",respuesta: "hola"},
                {verbo: "bye",respuesta: "adios"},
                {verbo: "sorry",respuesta: "perdon"},
                {verbo: "thank you",respuesta: "gracias"},
                {verbo: "stop",respuesta: "parar"},
                {verbo: "red",respuesta: "rojo"},
                {verbo: "blue",respuesta: "azul"},
                {verbo: "yellow",respuesta: "amarillo"},
                {verbo: "green",respuesta: "verde"},
                {verbo: "pink",respuesta: "rosa"},
                {verbo: "orange",respuesta: "naranja"},
                {verbo: "purple",respuesta: "morado"},
                {verbo: "brown",respuesta: "marron"},
                {verbo: "black",respuesta: "negro"},
                {verbo: "white",respuesta: "blanco"},
                
]

export default VerbosE;