let VerbosD = [{verbo: "readability",respuesta: "legibilidad"},
                {verbo: "lockdown",respuesta: "confinamiento"},
                {verbo: "destabilising",respuesta: "desestabilizador"},
                {verbo: "unlawfully",respuesta: "ilegalmente"}, 
                {verbo: "springboard",respuesta: "trampolin"}, 
                {verbo: "roadblock",respuesta: "barricada"},
                {verbo: "shipwrecked",respuesta: "naufrago"},
                {verbo: "enviromental",respuesta: "ambiental"},
                {verbo: "acknowledge",respuesta: "reconocer"},
                {verbo: "issuing",respuesta: "emisor"},
                {verbo: "dock",respuesta: "muelle"},
                {verbo: "lingering",respuesta: "persistente"},  
                {verbo: "thrive",respuesta: "prosperar"},
                {verbo: "rife",respuesta: "abundante"},
                {verbo: "appliances",respuesta: "electrodomesticos"},  
                {verbo: "ruling",respuesta: "fallo"},  
                {verbo: "undermine",respuesta: "socavar"},
                {verbo: "western",respuesta: "occidental"}, 
                {verbo: "stints",respuesta: "temporadas"}, 
                {verbo: "abroad",respuesta: "extranjero"}, 
                {verbo: "drilling",respuesta: "perforacion"},
                {verbo: "overturning",respuesta: "anular"},                
]

export default VerbosD;